News Email

diff --git a/.github/workflows/send-news-email.yml b/.github/workflows/send-news-email.yml
--- a/.github/workflows/send-news-email.yml
+++ b/.github/workflows/send-news-email.yml
@@ -18,17 +18,33 @@ jobs:
       - name: Ambil berita terkini
         id: fetch_news
         run: |
-          response=$(curl -s "https://api.currentsapi.services/v1/latest-news" -G -d language=en -d apiKey=${{ secrets.CURRENTSAPI_KEY }})    
-          echo "news_response=$response" >> $GITHUB_ENV  
-          echo "API Response: $response"  # Debugging step
+          response=$(curl -s -w "\n%{http_code}" "https://api.currentsapi.services/v1/latest-news" -G -d language=en -d apiKey=${{ secrets.CURRENTSAPI_KEY }})  
+          echo "API Response: $response"  # Debugging step  
+          http_code=$(echo "$response" | tail -n 1)  
+          echo "HTTP Code: $http_code"  # Debugging step  
+          echo "news_response=$(echo "$response" | head -n -1)" >> $GITHUB_ENV
+
+      - name: Periksa status kode HTTP
+        id: check_http_code
+        run: |
+          if [ "$http_code" -eq 200 ]; then  
+            echo "Status: Success"  
+          else  
+            echo "Status: Failed"  
+            echo "HTTP Code: $http_code"  
+            echo "Response: ${{ env.news_response }}"  
+            exit 1  
+          fi
 
       - name: Periksa apakah respons adalah JSON valid
         id: check_json
+        if: steps.check_http_code.outputs.Status == 'Success'
         run: |
           if echo ${{ env.news_response }} | jq empty 2>/dev/null; then  
             echo "JSON is valid"  
           else  
             echo "JSON is invalid"  
+            echo "Response: ${{ env.news_response }}"  
             exit 1  
           fi
 
